"use client";

import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import PageHeader from "@/components/layout/PageHeader";
import StatCard from "@/components/shared/StatCard";
import StatusPill from "@/components/shared/StatusPill";
import ItemIcon from "@/components/icons/items/ItemIcon";
import { useAppStore } from "@/stores/app-store";
import { formatCurrency, formatDate, formatDateTime } from "@/lib/utils";
import { MockRequisition } from "@/lib/data/mock-data";
import {
  Search, Eye, X, Check, Undo2,
  ChevronLeft, ChevronRight, Download,
  AlertTriangle, PackageCheck,
} from "lucide-react";

// ─── PDF generator for issuance voucher ─────────────────────────────────────
function downloadIssuancePDF(
  req: MockRequisition,
  approvedLines: { itemId: string; itemName: string; issuedQty: number; approvedQty: number; unitPrice: number }[],
  approverName: string,
  referenceNo: string
) {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(27, 42, 78);
  doc.text("STOCK ISSUANCE VOUCHER", pageW / 2, 18, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);
  doc.text("SRIMS — Stationery Requisition & Inventory Management System", pageW / 2, 25, { align: "center" });

  doc.setDrawColor(229, 231, 235);
  doc.line(14, 28, pageW - 14, 28);

  // Meta grid
  doc.setTextColor(55, 65, 81);
  doc.setFontSize(9);
  const issuedTotal = approvedLines.reduce((s, l) => s + l.issuedQty * l.unitPrice, 0);
  const requestedTotal = approvedLines.reduce((s, l) => s + l.approvedQty * l.unitPrice, 0);
  const isPartial = approvedLines.some((l) => l.issuedQty < l.approvedQty);

  const meta = [
    ["Requisition ID:", req.id, "Reference No:", referenceNo],
    ["Requested By:", req.userName, "Department:", req.departmentName],
    ["Approved By:", approverName, "Date of Issue:", formatDateTime(new Date().toISOString())],
    ["Purpose:", req.purpose || "—", "Required By:", formatDate(req.requiredDate)],
    ["Original Amount:", `₹${requestedTotal.toFixed(2)}`, "Issued Amount:", `₹${issuedTotal.toFixed(2)}${isPartial ? " (Partial)" : " (Full)"}`],
  ];
  let y = 36;
  for (const [l1, v1, l2, v2] of meta) {
    doc.setFont("helvetica", "bold"); doc.text(l1, 14, y);
    doc.setFont("helvetica", "normal"); doc.text(v1, 50, y);
    doc.setFont("helvetica", "bold"); doc.text(l2, 110, y);
    doc.setFont("helvetica", "normal"); doc.text(v2, 145, y);
    y += 6;
  }

  doc.line(14, y + 2, pageW - 14, y + 2);

  // Items table — "Requested Qty" = what was asked for, "Issued Qty" = what was actually given
  autoTable(doc, {
    startY: y + 6,
    head: [["#", "Item Name", "Requested Qty", "Issued Qty", "Unit", "Unit Price (₹)", "Issued Amount (₹)"]],
    body: approvedLines.map((line, i) => [
      i + 1,
      line.itemName,
      line.approvedQty,
      line.issuedQty,
      req.items.find((it) => it.itemId === line.itemId)?.unit || "—",
      line.unitPrice.toFixed(2),
      (line.issuedQty * line.unitPrice).toFixed(2),   // ← uses issued qty, not requested
    ]),
    foot: [[
      "", "TOTAL",
      approvedLines.reduce((s, l) => s + l.approvedQty, 0),
      approvedLines.reduce((s, l) => s + l.issuedQty, 0),
      "", "",
      "₹" + issuedTotal.toFixed(2),   // ← uses actual issued amount
    ]],
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: "bold", fontSize: 8 },
    footStyles: { fillColor: [243, 244, 246], textColor: [55, 65, 81], fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
  });

  // Signature lines
  const finalY = (doc as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 180;
  const sigY = finalY + 20;

  doc.setDrawColor(156, 163, 175);
  [14, 80, 146].forEach((x) => doc.line(x, sigY, x + 55, sigY));
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text("Approved By", 14, sigY + 5);
  doc.text("Issued By (Inventory)", 80, sigY + 5);
  doc.text("Received By (Employee)", 146, sigY + 5);

  doc.setFontSize(7);
  doc.text(`Generated by SRIMS on ${new Date().toLocaleString("en-IN")}`, pageW / 2, sigY + 16, { align: "center" });

  doc.save(`${referenceNo}_Issuance.pdf`);
}

// ─── Component ───────────────────────────────────────────────────────────────

interface IssueLine {
  itemId: string;
  itemName: string;
  requestedQty: number;
  availableStock: number;
  issuedQty: number;
  approvedQty: number;
  unitPrice: number;
  iconKey?: string;
}

export default function PendingApprovalsPage() {
  const { requisitions, stockItems, currentUser, approveAndIssue, updateRequisitionStatus, departments } = useAppStore();
  const [selectedReq, setSelectedReq] = useState<MockRequisition | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [departmentFilter, setDepartmentFilter] = useState("");
  const [priorityFilter, setPriorityFilter] = useState("");
  const [page, setPage] = useState(1);
  const perPage = 8;

  // Approve-and-issue modal state
  const [showApproveModal, setShowApproveModal] = useState(false);
  const [issueLines, setIssueLines] = useState<IssueLine[]>([]);
  const [issuedRef, setIssuedRef] = useState<string | null>(null);
  const [issuedReq, setIssuedReq] = useState<MockRequisition | null>(null);
  // Save the exact lines that were confirmed so the PDF reflects partial quantities
  const [confirmedLines, setConfirmedLines] = useState<IssueLine[]>([]);

  // Reject modal state
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [rejectComment, setRejectComment] = useState("");

  const pendingReqs = requisitions
    .filter((r) => r.status === "PENDING")
    .filter((r) => !departmentFilter || r.departmentName === departmentFilter)
    .filter((r) => !priorityFilter || r.priority === priorityFilter)
    .filter((r) => {
      if (!searchQuery) return true;
      const q = searchQuery.toLowerCase();
      return r.id.toLowerCase().includes(q) || r.userName.toLowerCase().includes(q);
    });

  const totalPages = Math.ceil(pendingReqs.length / perPage);
  const paginated = pendingReqs.slice((page - 1) * perPage, page * perPage);

  const todayReqs = pendingReqs.filter(
    (r) => new Date(r.createdAt).toDateString() === new Date().toDateString()
  ).length;
  const approvedThisMonth = requisitions.filter((r) => r.status === "APPROVED" || r.status === "ISSUED" || r.status === "PARTIAL").length;
  const rejectedCount = requisitions.filter((r) => r.status === "REJECTED").length;

  // Build issue lines from a requisition with live stock info
  const buildIssueLines = (req: MockRequisition): IssueLine[] =>
    req.items.map((item) => {
      const stockItem = stockItems.find((s) => s.id === item.itemId);
      const available = stockItem?.currentStock ?? 0;
      const issuable = Math.min(item.requestedQty, available);
      return {
        itemId: item.itemId,
        itemName: item.itemName,
        requestedQty: item.requestedQty,
        availableStock: available,
        issuedQty: issuable,
        approvedQty: item.requestedQty,
        unitPrice: item.unitPrice,
        iconKey: stockItem?.iconKey,
      };
    });

  const openApproveModal = (req: MockRequisition) => {
    setIssueLines(buildIssueLines(req));
    setShowApproveModal(true);
  };

  const handleConfirmApprove = () => {
    if (!selectedReq) return;
    const snapshotLines = [...issueLines]; // freeze the exact lines before any state clears
    const ref = approveAndIssue(
      selectedReq.id,
      snapshotLines.map((l) => ({
        itemId: l.itemId,
        itemName: l.itemName,
        issuedQty: l.issuedQty,
        approvedQty: l.approvedQty,
        unitPrice: l.unitPrice,
      })),
      currentUser.id,
      currentUser.name
    );
    setIssuedRef(ref);
    setIssuedReq(selectedReq);
    setConfirmedLines(snapshotLines); // ← save snapshot for correct PDF
    setShowApproveModal(false);
    setSelectedReq(null);
  };

  const handleReject = () => {
    if (!selectedReq || rejectComment.length < 10) return;
    updateRequisitionStatus(selectedReq.id, "REJECTED", {
      approvedById: currentUser.id,
      approvedByName: currentUser.name,
      rejectedReason: rejectComment,
    });
    setShowRejectModal(false);
    setRejectComment("");
    setSelectedReq(null);
  };

  const handleSendBack = (req: MockRequisition) => {
    updateRequisitionStatus(req.id, "DRAFT");
    setSelectedReq(null);
  };

  const totalIssueAmount = issueLines.reduce((s, l) => s + l.issuedQty * l.unitPrice, 0);
  const hasStockShortage = issueLines.some((l) => l.availableStock < l.requestedQty);

  return (
    <div>
      <PageHeader title="Pending Approvals" subtitle="Review and approve or reject requisitions" />

      {/* Success banner after approve-and-issue */}
      {issuedRef && issuedReq && confirmedLines.length > 0 && (
        <div className="mb-4 flex items-center justify-between rounded-card border border-green-200 bg-green-50 px-4 py-3">
          <div className="flex items-center gap-2 text-green-800">
            <PackageCheck size={18} />
            <div>
              <p className="text-[13px] font-semibold">
                {issuedReq.id} — approved and stock issued ({issuedRef})
              </p>
              <p className="text-[12px] opacity-75">
                Issued: {confirmedLines.reduce((s, l) => s + l.issuedQty, 0)} items
                &nbsp;·&nbsp;
                Total: {formatCurrency(confirmedLines.reduce((s, l) => s + l.issuedQty * l.unitPrice, 0))}
                {confirmedLines.some((l) => l.issuedQty < l.requestedQty) &&
                  " (partial — some items had insufficient stock)"}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => downloadIssuancePDF(
                issuedReq,
                confirmedLines.map((l) => ({
                  itemId: l.itemId,
                  itemName: l.itemName,
                  issuedQty: l.issuedQty,
                  approvedQty: l.approvedQty,
                  unitPrice: l.unitPrice,
                })),
                currentUser.name,
                issuedRef
              )}
              className="flex items-center gap-1.5 rounded-button border border-green-300 bg-white px-3 py-1.5 text-[12px] font-medium text-green-700 hover:bg-green-100"
            >
              <Download size={14} />
              Download PDF
            </button>
            <button onClick={() => { setIssuedRef(null); setIssuedReq(null); setConfirmedLines([]); }} className="text-green-600 hover:text-green-800">
              <X size={16} />
            </button>
          </div>
        </div>
      )}

      {/* Stat Strip */}
      <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatCard icon="Hourglass"    iconTint="amber"  label="Pending Now"      value={pendingReqs.length} />
        <StatCard icon="Calendar"     iconTint="amber"  label="Received Today"   value={todayReqs} />
        <StatCard icon="CheckCircle2" iconTint="green"  label="Approved / Issued" value={approvedThisMonth} />
        <StatCard icon="XCircle"      iconTint="red"    label="Rejected"         value={rejectedCount} />
      </div>

      {/* Body */}
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-5">
        {/* List */}
        <div className={selectedReq ? "lg:col-span-3" : "lg:col-span-5"}>
          <div className="rounded-card border border-border bg-surface-card">
            <div className="flex flex-wrap items-center gap-2 border-b border-border px-4 py-3">
              <div className="relative flex-1 min-w-[180px]">
                <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" />
                <input
                  type="text"
                  placeholder="Search..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full rounded-button border border-border py-2 pl-9 pr-3 text-[13px] placeholder:text-text-muted focus:border-brand-primary focus:outline-none"
                />
              </div>
              <select
                value={departmentFilter}
                onChange={(e) => { setDepartmentFilter(e.target.value); setPage(1); }}
                className="rounded-button border border-border px-3 py-2 text-[12px] text-text-secondary focus:outline-none"
              >
                <option value="">All Departments</option>
                {departments.map((d) => <option key={d.id} value={d.name}>{d.name}</option>)}
              </select>
              <select
                value={priorityFilter}
                onChange={(e) => { setPriorityFilter(e.target.value); setPage(1); }}
                className="rounded-button border border-border px-3 py-2 text-[12px] text-text-secondary focus:outline-none"
              >
                <option value="">All Priorities</option>
                <option value="URGENT">Urgent</option>
                <option value="NORMAL">Normal</option>
                <option value="LOW">Low</option>
              </select>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border">
                    {["REQ No.", "Requested By", "Department", "Date", "Items", "Amount", "Priority", "Action"].map((h) => (
                      <th key={h} className={`px-4 py-3 text-table-header uppercase tracking-table-header text-text-secondary ${
                        ["Items", "Amount"].includes(h) ? "text-right" : ["Action"].includes(h) ? "text-center" : "text-left"
                      }`}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {paginated.length === 0 ? (
                    <tr><td colSpan={8} className="px-4 py-12 text-center text-[14px] text-text-muted">
                      No pending requisitions
                    </td></tr>
                  ) : paginated.map((req) => (
                    <tr
                      key={req.id}
                      className={`border-b border-border last:border-0 cursor-pointer transition-colors ${
                        selectedReq?.id === req.id ? "bg-blue-50" : "hover:bg-gray-50"
                      }`}
                      onClick={() => setSelectedReq(req)}
                    >
                      <td className="px-4 py-3 text-[13px] font-medium text-brand-primary">{req.id}</td>
                      <td className="px-4 py-3 text-[13px] text-text-primary">{req.userName}</td>
                      <td className="px-4 py-3 text-[13px] text-text-secondary">{req.departmentName}</td>
                      <td className="px-4 py-3 text-[13px] text-text-secondary">{formatDate(req.createdAt)}</td>
                      <td className="px-4 py-3 text-right text-[13px]">{req.items.length}</td>
                      <td className="px-4 py-3 text-right text-[13px] font-medium">{formatCurrency(req.totalAmount)}</td>
                      <td className="px-4 py-3">
                        <span className={`inline-block rounded-full px-2 py-0.5 text-[10px] font-semibold ${
                          req.priority === "URGENT" ? "bg-red-100 text-red-700"
                          : req.priority === "NORMAL" ? "bg-blue-100 text-blue-700"
                          : "bg-gray-100 text-gray-600"
                        }`}>
                          {req.priority}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-center">
                        <button className="rounded p-1.5 text-text-secondary hover:bg-gray-100 hover:text-brand-primary">
                          <Eye size={16} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {totalPages > 1 && (
              <div className="flex items-center justify-between border-t border-border px-4 py-3">
                <span className="text-[12px] text-text-secondary">
                  {(page - 1) * perPage + 1}–{Math.min(page * perPage, pendingReqs.length)} of {pendingReqs.length}
                </span>
                <div className="flex gap-1">
                  <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="rounded p-1 text-text-secondary hover:bg-gray-100 disabled:opacity-30"><ChevronLeft size={16} /></button>
                  <button onClick={() => setPage(p => Math.min(totalPages, p + 1))} disabled={page === totalPages} className="rounded p-1 text-text-secondary hover:bg-gray-100 disabled:opacity-30"><ChevronRight size={16} /></button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Detail panel */}
        {selectedReq && (
          <div className="lg:col-span-2">
            <div className="sticky top-[88px] rounded-card border border-border bg-surface-card p-4">
              <div className="mb-3 flex items-start justify-between">
                <div>
                  <h3 className="text-[15px] font-bold text-text-primary">{selectedReq.id}</h3>
                  <StatusPill variant="pending" className="mt-1" />
                </div>
                <button onClick={() => setSelectedReq(null)} className="rounded p-1 text-text-muted hover:bg-gray-100">
                  <X size={16} />
                </button>
              </div>

              <div className="mb-3 grid grid-cols-2 gap-2 text-[12px]">
                {[
                  ["Requested By", selectedReq.userName],
                  ["Department", selectedReq.departmentName],
                  ["Submitted", formatDate(selectedReq.createdAt)],
                  ["Required By", formatDate(selectedReq.requiredDate)],
                  ["Purpose", selectedReq.purpose],
                  ["Priority", selectedReq.priority.charAt(0) + selectedReq.priority.slice(1).toLowerCase()],
                ].map(([label, value]) => (
                  <div key={label}>
                    <span className="text-[10px] uppercase text-text-muted">{label}</span>
                    <p className="font-medium text-text-primary">{value}</p>
                  </div>
                ))}
              </div>

              {/* Items with live stock info */}
              <div className="mb-3 overflow-hidden rounded-md border border-border">
                <table className="w-full text-[11px]">
                  <thead>
                    <tr className="bg-gray-50 border-b border-border">
                      <th className="px-2 py-1.5 text-left font-semibold text-text-secondary uppercase tracking-wide">Item</th>
                      <th className="px-2 py-1.5 text-right font-semibold text-text-secondary uppercase tracking-wide">Req.</th>
                      <th className="px-2 py-1.5 text-right font-semibold text-text-secondary uppercase tracking-wide">In Stock</th>
                    </tr>
                  </thead>
                  <tbody>
                    {selectedReq.items.map((item) => {
                      const stock = stockItems.find((s) => s.id === item.itemId);
                      const available = stock?.currentStock ?? 0;
                      const shortage = available < item.requestedQty;
                      return (
                        <tr key={item.id} className="border-b border-border last:border-0">
                          <td className="px-2 py-1.5">
                            <div className="flex items-center gap-1.5">
                              <ItemIcon iconKey={stock?.iconKey} itemId={item.itemId} size={16} />
                              <span className="text-text-primary">{item.itemName}</span>
                            </div>
                          </td>
                          <td className="px-2 py-1.5 text-right">{item.requestedQty}</td>
                          <td className={`px-2 py-1.5 text-right font-semibold ${shortage ? "text-red-600" : "text-green-600"}`}>
                            {available}
                            {shortage && <AlertTriangle size={10} className="ml-1 inline" />}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

              {/* Action buttons */}
              <div className="flex gap-2">
                <button
                  onClick={() => setShowRejectModal(true)}
                  className="flex flex-1 items-center justify-center gap-1.5 rounded-button border border-red-300 px-3 py-2 text-[12px] font-medium text-red-600 hover:bg-red-50"
                >
                  <X size={13} /> Reject
                </button>
                <button
                  onClick={() => handleSendBack(selectedReq)}
                  className="flex flex-1 items-center justify-center gap-1.5 rounded-button border border-border px-3 py-2 text-[12px] font-medium text-brand-primary hover:bg-blue-50"
                >
                  <Undo2 size={13} /> Send Back
                </button>
                <button
                  onClick={() => openApproveModal(selectedReq)}
                  className="flex flex-1 items-center justify-center gap-1.5 rounded-button bg-green-600 px-3 py-2 text-[12px] font-semibold text-white hover:bg-green-700"
                >
                  <Check size={13} /> Approve & Issue
                </button>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ─── Approve & Issue modal ─── */}
      {showApproveModal && selectedReq && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-card bg-surface-card shadow-lg">
            <div className="flex items-center justify-between border-b border-border px-5 py-4">
              <div>
                <h3 className="text-[16px] font-bold text-text-primary">Approve & Issue Stock</h3>
                <p className="text-[12px] text-text-secondary">
                  {selectedReq.id} — {selectedReq.userName} ({selectedReq.departmentName})
                </p>
              </div>
              <button onClick={() => setShowApproveModal(false)} className="text-text-muted hover:text-text-primary">
                <X size={18} />
              </button>
            </div>

            <div className="p-5">
              {hasStockShortage && (
                <div className="mb-4 flex items-center gap-2 rounded-md border border-amber-200 bg-amber-50 px-3 py-2.5 text-[12px] text-amber-800">
                  <AlertTriangle size={15} />
                  Some items have insufficient stock. Adjust issue quantities below or approve partially.
                </div>
              )}

              <table className="w-full text-[12px]">
                <thead>
                  <tr className="border-b border-border">
                    <th className="pb-2 text-left font-semibold text-text-secondary uppercase tracking-wide text-[10px]">Item</th>
                    <th className="pb-2 text-right font-semibold text-text-secondary uppercase tracking-wide text-[10px]">Requested</th>
                    <th className="pb-2 text-right font-semibold text-text-secondary uppercase tracking-wide text-[10px]">In Stock</th>
                    <th className="pb-2 text-right font-semibold text-text-secondary uppercase tracking-wide text-[10px] w-24">Issue Qty</th>
                    <th className="pb-2 text-right font-semibold text-text-secondary uppercase tracking-wide text-[10px]">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {issueLines.map((line, idx) => {
                    const shortage = line.availableStock < line.requestedQty;
                    return (
                      <tr key={line.itemId} className="border-b border-border last:border-0">
                        <td className="py-2">
                          <div className="flex items-center gap-2">
                            <ItemIcon iconKey={line.iconKey} itemId={line.itemId} size={20} />
                            <span className="text-text-primary">{line.itemName}</span>
                          </div>
                        </td>
                        <td className="py-2 text-right text-text-secondary">{line.requestedQty}</td>
                        <td className={`py-2 text-right font-semibold ${shortage ? "text-red-600" : "text-green-600"}`}>
                          {line.availableStock}
                        </td>
                        <td className="py-2 text-right">
                          <input
                            type="number"
                            value={line.issuedQty}
                            min={0}
                            max={line.availableStock}
                            onChange={(e) => {
                              const v = Math.max(0, Math.min(line.availableStock, parseInt(e.target.value) || 0));
                              setIssueLines(prev => prev.map((l, i) =>
                                i === idx ? { ...l, issuedQty: v } : l
                              ));
                            }}
                            className={`w-20 rounded-button border px-2 py-1 text-right text-[12px] focus:outline-none ${
                              shortage ? "border-amber-300 bg-amber-50 focus:border-amber-500" : "border-border focus:border-brand-primary"
                            }`}
                          />
                        </td>
                        <td className="py-2 text-right font-medium text-text-primary">
                          {formatCurrency(line.issuedQty * line.unitPrice)}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
                <tfoot>
                  <tr className="border-t border-border bg-gray-50">
                    <td colSpan={4} className="px-0 py-2 text-right font-bold text-text-primary">Total Issued Amount</td>
                    <td className="py-2 text-right font-bold text-brand-primary">{formatCurrency(totalIssueAmount)}</td>
                  </tr>
                </tfoot>
              </table>

              <div className="mt-5 flex justify-end gap-3">
                <button
                  onClick={() => setShowApproveModal(false)}
                  className="rounded-button border border-border px-4 py-2 text-[13px] text-text-secondary hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  onClick={handleConfirmApprove}
                  disabled={issueLines.every((l) => l.issuedQty === 0)}
                  className="flex items-center gap-2 rounded-button bg-green-600 px-5 py-2 text-[13px] font-semibold text-white hover:bg-green-700 disabled:opacity-40"
                >
                  <Check size={15} />
                  Confirm — Approve & Issue
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Reject modal */}
      {showRejectModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="w-full max-w-md rounded-card bg-surface-card p-6 shadow-lg">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-[16px] font-semibold text-text-primary">Reject Requisition</h3>
              <button onClick={() => setShowRejectModal(false)} className="text-text-muted hover:text-text-primary"><X size={18} /></button>
            </div>
            <p className="mb-3 text-[13px] text-text-secondary">Please provide a reason (min 10 characters).</p>
            <textarea
              value={rejectComment}
              onChange={(e) => setRejectComment(e.target.value)}
              rows={4}
              placeholder="Enter rejection reason..."
              className="w-full rounded-button border border-border px-3 py-2 text-[14px] placeholder:text-text-muted focus:border-red-400 focus:outline-none resize-none"
            />
            <div className="mt-1 text-right text-[11px] text-text-muted">{rejectComment.length} / 10 min</div>
            <div className="mt-4 flex justify-end gap-2">
              <button onClick={() => { setShowRejectModal(false); setRejectComment(""); }} className="rounded-button border border-border px-4 py-2 text-[13px] text-text-secondary hover:bg-gray-50">Cancel</button>
              <button onClick={handleReject} disabled={rejectComment.length < 10} className="rounded-button bg-red-600 px-4 py-2 text-[13px] font-semibold text-white hover:bg-red-700 disabled:opacity-40">
                Confirm Reject
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
